// Code generated by GoVPP's binapi-generator. DO NOT EDIT.

package ping

import (
	"context"

	api "go.fd.io/govpp/api"
)

// RPCService defines RPC service ping.
type RPCService interface {
	WantPingEvents(ctx context.Context, in *WantPingEvents) (*WantPingEventsReply, error)
}

type serviceClient struct {
	conn api.Connection
}

func NewServiceClient(conn api.Connection) RPCService {
	return &serviceClient{conn}
}

func (c *serviceClient) WantPingEvents(ctx context.Context, in *WantPingEvents) (*WantPingEventsReply, error) {
	out := new(WantPingEventsReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}
