// Code generated by GoVPP's binapi-generator. DO NOT EDIT.

package tracedump

import (
	"context"
	"fmt"
	"io"

	api "git.fd.io/govpp.git/api"
)

// RPCService defines RPC service  tracedump.
type RPCService interface {
	TraceDump(ctx context.Context, in *TraceDump) (RPCService_TraceDumpClient, error)
}

type serviceClient struct {
	conn api.Connection
}

func NewServiceClient(conn api.Connection) RPCService {
	return &serviceClient{conn}
}

func (c *serviceClient) TraceDump(ctx context.Context, in *TraceDump) (RPCService_TraceDumpClient, error) {
	stream, err := c.conn.NewStream(ctx)
	if err != nil {
		return nil, err
	}
	x := &serviceClient_TraceDumpClient{stream}
	if err := x.Stream.SendMsg(in); err != nil {
		return nil, err
	}
	return x, nil
}

type RPCService_TraceDumpClient interface {
	Recv() (*TraceDetails, error)
	api.Stream
}

type serviceClient_TraceDumpClient struct {
	api.Stream
}

func (c *serviceClient_TraceDumpClient) Recv() (*TraceDetails, error) {
	msg, err := c.Stream.RecvMsg()
	if err != nil {
		return nil, err
	}
	switch m := msg.(type) {
	case *TraceDetails:
		return m, nil
	case *TraceDumpReply:
		return nil, io.EOF
	default:
		return nil, fmt.Errorf("unexpected message: %T %v", m, m)
	}
}
